In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:


#one neuron with four inputs and one output

inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2


output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias
print(output)

4.8


In [3]:
#three neurons with four inputs and each have single output

weights1=[0.2,0.8,-0.5,1.0]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[0.26,0.27,0.17,0.87]

bias1=2
bias2=3
bias3=0.5

#outputs from three neurons
output= [inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
         inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
         inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
print(output)
       

[4.8, 1.21, 3.985]


In [4]:
##a more compact technique
inputs=[1,2,3,2.5]

weights=[[0.2,0.8,-0.5,1.0],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

# layer_outputs=[]
# for neuron_weights,neuron_bias in zip(weights,biases): #zip combines two lists element-wise
#     neuron_output=0
#     for n_input,weight in zip(inputs,neuron_weights):
#         neuron_output+=n_input*weight
#     neuron_output+=neuron_bias
#     layer_outputs.append(neuron_output)
# # print(layer_outputs)


'''DOT PRODUCT'''
'''USED TO MULTIPLY ELMENT WISE INPUTS AND BIASES IN NN CALCULATIONS'''
# inputs=[1,2,3,2.5]
# weights=[0.2,0.8,-0.5,1.0]
# bias=2

output=np.dot(weights,inputs)+bias  #element wise multiplication meaning weights[0]*input + bias and simliar
print(output)

[4.8   0.21  3.885]


In [5]:
'''BATCH'''
inputs=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]
weights=[[0.2,0.8,-0.5,1.0],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]] 
biases=[2,3,0.5]
weights2=[[0.1,-0.14,0.5],
         [-0.5,0.12,-0.33],
         [-0.44,0.73,-0.13]] 
biases2=[-1,2,-0.5]
#layer 1 has 4 inputs 3 outputs and layer 2 has 3 inputs from layer 1 outputs and 3 outputs
#the number of nodes(uniques sets of weights and biases) define the number of outputs
#clearly 
layer1_outputs=np.dot(inputs,np.array(weights).T)+biases
layer2_outputs=np.dot(layer1_outputs,np.array(weights2).T)+biases2

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [6]:
"""OBJECTS"""

#input data to out neural network
#we have three samples
np.random.seed(0)


#the shape here is the nuumber of neurons x no. of inputs
#we have three inputs here
#each input is made up of 4 independent variables
X= [[1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]]

class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.1*np.random.randn(n_inputs,n_neurons) #this is reversed to eliminate transpose later on
        self.biases=np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights)+self.biases

layer1=Layer_Dense(4,5)
layer2=Layer_Dense(5,2) #regardless of these values the number of rows is gonna be same in each output because it denotes the number of samples, only change is column number

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

###if you don't understand it at once, think deeply and give time, you had once understood this so its just a matter of time and effort

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [7]:
inputs=[0,2,-1,3.3,-2.7,1.1,2.2,-100]
output=[]

#Rectified linear function
for i in inputs:
    # if i > 0:
    #     output.append(i)
    # elif i<=0:
    #     output.append(0)
    output.append(max(0,i))
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [8]:
#ACTIVATION FUNCTIONS

def create_data(points,classes):
    X=np.zeros((points*classes,2))
    y=np.zeros(points*classes,dtype='uint8')
    for class_number in range(classes):
        ix=range(points*class_number,points*(class_number+1))
        r=np.linspace(0.0,1,points)
        t=np.linspace(class_number*4,(class_number+1)*4,points)+np.random.randn(points)*0.2
        X[ix]=np.c_[r*np.sin(t*2.5),r*np.cos(t*2.5)]
        y[ix]=class_number
    return X,y
X,y=create_data(100,3)
# for class_number in range(3):
#     class_indices = np.where(y == class_number)[0]
#     plt.scatter(X[class_indices, 0], X[class_indices, 1], label=f'Class {class_number}')
# plt.legend()
# plt.show()

#now we are gonna deal with the layers in the neural network
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.1*np.random.randn(n_inputs,n_neurons) #this is reversed to eliminate transpose later on
        self.biases=np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights)+self.biases

class Activation_ReLU:
    def forward(self,inputs):
        self.output=np.maximum(0,inputs)

layer1=Layer_Dense(2,5)
activation1=Activation_ReLU()

layer1.forward(X)
activation1.forward(layer1.output)

# layer1.output
activation1.output


array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.00080274, 0.        , 0.00065987, 0.        , 0.00083796],
       [0.00082768, 0.        , 0.0005103 , 0.        , 0.00454176],
       ...,
       [0.01800099, 0.        , 0.00336391, 0.        , 0.26602511],
       [0.        , 0.16360456, 0.        , 0.13192221, 0.20328078],
       [0.        , 0.        , 0.        , 0.05579987, 0.31271706]])

In [27]:
'''SOFTMAX ACTIVATION FUNCTION'''
import math
import numpy as np

layeroutputs=[[4.8,1.21,2.385],
              [8.9,-1.81,0.2],
              [1.41,1.051,0.026]]

exp_values=np.exp(layeroutputs)
print(exp_values)
# New_exp_values=np.max(exp_values,axis=1,keepdims=True)
# print(New_exp_values)
# print(exp_values)


norm_values=exp_values/np.sum(exp_values,axis=1,keepdims=True)
print(norm_values)

# print(norm_values)
# print(sum(norm_values))






[[1.21510418e+02 3.35348465e+00 1.08590627e+01]
 [7.33197354e+03 1.63654137e-01 1.22140276e+00]
 [4.09595540e+00 2.86051020e+00 1.02634095e+00]]
[[1.21510418e+02]
 [7.33197354e+03]
 [4.09595540e+00]]
[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [33]:
#ACTIVATION FUNCTIONS

def create_data(points,classes):
    X=np.zeros((points*classes,2))
    y=np.zeros(points*classes,dtype='uint8')
    for class_number in range(classes):
        ix=range(points*class_number,points*(class_number+1))
        r=np.linspace(0.0,1,points)
        t=np.linspace(class_number*4,(class_number+1)*4,points)+np.random.randn(points)*0.2
        X[ix]=np.c_[r*np.sin(t*2.5),r*np.cos(t*2.5)]
        y[ix]=class_number
    return X,y
X,y=create_data(100,3)

class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.1*np.random.randn(n_inputs,n_neurons) #this is reversed to eliminate transpose later on
        self.biases=np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights)+self.biases

class Activation_ReLU:
    def forward(self,inputs):
        self.output=np.maximum(0,inputs)

class Activation_Softmax:
    def forward(self,inputs):
        exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
        probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
        self.output=probabilities

dense1=Layer_Dense(2,3)
Activation1=Activation_ReLU()
dense2=Layer_Dense(3,3)
Activation2=Activation_Softmax()

dense1.forward(X)
Activation1.forward(dense1.output)
dense2.forward(Activation1.output)
Activation2.forward(dense2.output)

print(Activation2.output)

[[0.33333333 0.33333333 0.33333333]
 [0.33335766 0.33332326 0.33331908]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33329324 0.33352161 0.33318516]
 [0.33333333 0.33333333 0.33333333]
 [0.33325475 0.33370211 0.33304314]
 [0.33333791 0.33333144 0.33333065]
 [0.33326499 0.3336541  0.33308091]
 [0.3332548  0.33370189 0.33304331]
 [0.3331655  0.33411999 0.33271451]
 [0.33333333 0.33333333 0.33333333]
 [0.33321239 0.3339006  0.33288701]
 [0.33316321 0.33413072 0.33270608]
 [0.33318544 0.33402674 0.33278782]
 [0.33324289 0.33455247 0.33220463]
 [0.33310405 0.33440712 0.33248883]
 [0.3338309  0.33423708 0.33193202]
 [0.33346317 0.33466808 0.33186875]
 [0.33352585 0.33470242 0.33177173]
 [0.33342318 0.33485191 0.33172491]
 [0.3330005  0.3348899  0.3321096 ]
 [0.33304801 0.33516971 0.33178227]
 [0.33385056 0.33473505 0.33141439]
 [0.33407064 0.33456356 0.3313658 ]
 [0.3349522  0.33366179 0.33138601]
 [0.33359254 0.33520951 0.33119795]
 [0.33344919 0.33538655 0.33

In [ ]:
'''LOSS FUNCTION'''

