In [2]:
import numpy as np

In [5]:


#one neuron with four inputs and one output

inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2


output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias
print(output)

4.8


In [6]:
#three neurons with four inputs and each have single output

weights1=[0.2,0.8,-0.5,1.0]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[0.26,0.27,0.17,0.87]

bias1=2
bias2=3
bias3=0.5

#outputs from three neurons
output= [inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
         inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
         inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
print(output)
       

[4.8, 1.21, 3.985]


In [10]:
##a more compact technique
inputs=[1,2,3,2.5]

weights=[[0.2,0.8,-0.5,1.0],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

# layer_outputs=[]
# for neuron_weights,neuron_bias in zip(weights,biases): #zip combines two lists element-wise
#     neuron_output=0
#     for n_input,weight in zip(inputs,neuron_weights):
#         neuron_output+=n_input*weight
#     neuron_output+=neuron_bias
#     layer_outputs.append(neuron_output)
# # print(layer_outputs)


'''DOT PRODUCT'''
'''USED TO MULTIPLY ELMENT WISE INPUTS AND BIASES IN NN CALCULATIONS'''
# inputs=[1,2,3,2.5]
# weights=[0.2,0.8,-0.5,1.0]
# bias=2

output=np.dot(weights,inputs)+bias  #element wise multiplication meaning weights[0]*input + bias and simliar
print(output)

[4.8   0.21  3.885]


In [10]:
'''BATCH'''
inputs=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]
weights=[[0.2,0.8,-0.5,1.0],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]] 
biases=[2,3,0.5]
weights2=[[0.1,-0.14,0.5],
         [-0.5,0.12,-0.33],
         [-0.44,0.73,-0.13]] 
biases2=[-1,2,-0.5]
#layer 1 has 4 inputs 3 outputs and layer 2 has 3 inputs from layer 1 outputs and 3 outputs
#the number of nodes(uniques sets of weights and biases) define the number of outputs
#clearly 
layer1_outputs=np.dot(inputs,np.array(weights).T)+biases
layer2_outputs=np.dot(layer1_outputs,np.array(weights2).T)+biases2

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [24]:
"""OBJECTS"""

#input data to out neural network
#we have three samples
np.random.seed(0)


#the shape here is the nuumber of neurons x no. of inputs
X= [[1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]]

#now we are gonna deal with the layers in the neural network
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.1*np.random.randn(n_inputs,n_neurons) #this is reversed to eliminate transpose later on
        self.biases=np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights)+self.biases

layer1=Layer_Dense(4,5)
layer2=Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
